name: test
  


on:
    push:
        branches:
            - main

jobs:
    job-1:
      runs-on: ubuntu-latest 
      steps:
        - run: echo "Hello, World!"
    
    job-2:
      runs-on: ubuntu-latest
      needs: job-1
      steps:
        - run: echo "This job depends on job-1"
    job-3:
        runs-on: ubuntu-latest
        needs: [job-1, job-2]
        steps:
            - run: echo "This job depends on both job-1 and job-2"
            - run: echo "This job runs after job-1 and job-2"