name: first_work 

on:
  push:
    branches:
      - main

jobs:
  exmp-job:
    runs-on: ubuntu-latest 


    steps:
      - name: Print welcom sidoooo
        run: echo "welcom sido how are you"
    
  
